version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
