source 'https://rubygems.org'

gem 'middleman', '~> 4.0'
gem 'middleman-core'
gem 'middleman-blog'
gem 'middleman-syntax'
gem 'builder'
gem 'middleman-livereload'
gem 'jquery-middleman'
gem 'nokogiri'
gem 'ffi'
gem 'redcarpet'
